<?php
  /**
   *
   */
  class Tracer
  {

    function __construct()
    {
      // echo json_encode($data);
      // die;
      date_default_timezone_set('Asia/Manila');
      $this->page = 1;
      $this->pdf = new FPDF('L');
      $this->employee = Functions::name_format(Session::get('fname'), Session::get('lname'), Session::get('mname'), true, Session::get('suffix'));
      $this->date_today = date('F d, Y h:i a');
      $this->data = [];
    }

    private function _initpdf(){
      $this->totalPage = count($this->data);
      $this->pdf->AddFont('Calibri','','Calibri.php');
      $this->pdf->AddFont('BodoniMTBlack','B','BodoniMTBlack.php');
      $this->pdf->AddFont('Calibri Bold','B','Calibri Bold.php');
      $this->pdf->SetMargins(5, 0, 0);
    }

    private function _headerInfo($n){
      $this->pdf->setY(32);
      $this->pdf->SetFont('Calibri','',12);
      $this->pdf->Cell(0,4,'TRACER STUDY',0,1,'C',false);
      $this->pdf->setXY(20,40);
      $this->pdf->SetFont('Calibri Bold','B',12);
      $this->pdf->SetFont('Calibri Bold','B',12);
      $this->pdf->setXY(20,45);
      $this->pdf->Cell(25,2,'NUMBER OF RESPONDENTS : '.$n,0,0,'L',false);
      $this->pdf->SetFont('Calibri','',12);
      $this->pdf->Cell(20,2,'',0,1,'L',false);
    }

    private function _createHeader($n){
      $this->pdf->AddPage();
      $this->pdf->Image(URL."public/img/pdfimgs/puplogo.png", 140, 2, 15);
      $this->pdf->setY(17);
      $this->pdf->SetFont('Calibri Bold','B',12);
      $this->pdf->Cell(0,4,'POLYTECHNIC UNIVERSITY OF THE PHILIPPINES',0,1,'C',false);
      $this->pdf->SetFont('Calibri','',11);
      $this->pdf->SetTextColor(92,92,92);
      $this->pdf->Cell(0,4,'A. Mabini Campus, Anonas Street, Sta. Mesa, Manila, Philippines 1016',0,1,'C',false);
      $this->pdf->Cell(0,4,'(632) 335-1787 or 335-1777 local 293',0,1,'C',false);
      $this->pdf->SetTextColor(0,0,0);
      $this->pdf->setXY(275,6);
      $this->pdf->Cell(10,2,'Page '.$this->page.'/'.$this->totalPage,0,1,'C',false);
      $this->_headerInfo($n);
    }
    private function _createFooter(){
      $this->pdf->SetAutoPageBreak(true,1);
      $this->pdf->setY(197);
      $this->pdf->SetFont('Calibri','',12);
      $this->pdf->Cell(0,4,'Generated By: '.$this->employee,0,0,'L',false);
      $this->pdf->Cell(0,4,'Date & Time: '.$this->date_today,0,0,'R',false);
    }

    private function _bodyHeaders($category){
      $this->pdf->setY(54);
      $this->pdf->SetFont('Calibri Bold','B',11);
    }
    private function _bodyData($question){
      $this->pdf->setXY(50, 69);
      $this->pdf->SetFont('Calibri Bold','B',16);
      $this->pdf->Cell(0,4,$question['question'],0,0,'L',false);
      $this->pdf->SetFont('Calibri','',14);
      $y = 90;
      foreach ($question['choices'] as $choice) {
        $this->pdf->setXY(47, $y);
        $this->pdf->Cell(200,6,$choice['description'],'TLB',0,'L',false);
        $this->pdf->Cell(15,6,number_format((($choice['take'] / $question['take']) * 100),2).'%','TRB',0,'R',false);
        $this->pdf->Cell(15,6,$choice['take'],0,1,'R',false);
        $y+=15;
      }
    }

    private function _createBody(){
      foreach ($this->data as $question) {
        $this->_createHeader($question['take']);
        $this->_bodyData($question);
        $this->_createFooter();
        $this->page++;
      }
      $this->_createFooter();
    }

    public function generate($id){
      $this->_initpdf();
      $this->_createBody();
      $this->pdf->output('I', $id.'.pdf');
    }

  }
